### ISSUE TITLE
Weather table expands on update

### ISSUE THREAD

**Issue by Conroman16** [GolfWithFriends/golf-with-friends#5]
The weather table expands horizontally when 5-minute update interval expires and the weather data updates.  I have no idea why this is happening

**Comment by thedustinsmith** [comment]
This was a weird issue.  At first I fixed it by setting the width and height statically every time we draw.  That seemed kind of like a hacky fix.

Eventually I cached the chart in a variable.  The problem was every time you declared a new Chart() ChartJS thought it was being performed on a new canvas so it scaled it every time.

Here's the SO post that explains why ChartJS scales the canvas:
http://stackoverflow.com/questions/19847582/chart-js-canvas-resize

**Comment by Conroman16** [comment]
Gah makes perfect sense.  I hadn't considered the fact that I was drawing a new chart each time.  Thanks for looking into that
